version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
    # command waits for db to be ready, before running any scripts to avoid errors. 
    command: >
      bash -c "
        while !</dev/tcp/db/5432; do sleep 1; done;
        python db/seed_db.py;
        python main.py;
      "